# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
install! 'cocoapods', :disable_input_output_paths => true
target 'demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for demo
  pod 'IRPhotoGallery'
#  pod 'IRPhotoGallery', :path => '../IRPhotoGallery/'
#  pod 'IRCameraViewController', :path => '../../IRCameraViewController/IRCameraViewController.podspec'
#  pod 'IRPhotoGallery', :podspec => '../IRPhotoGallery/IRPhotoGallery.podspec'
end
